# Data Cleaning in Pandas - Introduction

## Introduction

In this section, you will learn invaluable skills that will form the foundation of your data processing work. Before you can apply machine learning algorithms or do interesting analyses, you often must clean and transform your data into a suitable format. Such initial data wrangling processes are often referred to as Extract Transform Load (ETL). Our primary tool of choice for performing ETL and basic analyses will be the Pandas package.

## Why ETL?

ETL is an essential first step to data analysis and data science. It also will form the foundation for exploratory data analysis. Often, you will be thrown a dataset that you have little to no information about. In these cases, your first step is to explore the data and get familiar with it. What are the columns? How many observations do you have? Are there missing values? Any outliers? If we have user-level data, how can we explore aggregate trends along features like gender, race, or geography? All of these can be answered by applying ETL to transform raw datasets into alternative useful views.

Extract(APIs, websites, PDF Documents)
Transform: Data cleaning- Check for missing values, outliers, data types
Load: Database (Relational Databases- MYSQL, Non relational: MongoDB, Oracle) Use python to save the cleaned file. 
Read the data and perform

## Quick ETL Example

While you'll see complete examples and explanations for all of these techniques (and more), here's a quick preview of some ETL techniques covered in this section.

### Import data

In [15]:
#Load the pandas library

import pandas as pd
pd.set_option('display

In [17]:

#Read the data and save it to a df variable
df = pd.read_csv('Yelp_Reviews.csv', index_col=0)

#Preview the first 5 rows
df.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg

In [21]:
#F Find the number of rows and columns
df.shape
print(f'The number of rows are {df.shape[0]} and the number of columns are {df.shape[1]}')

The number of rows are 2610 and the number of columns are 9

In [23]:
# Preview the column names
df.columns

Index(['business_id', 'cool', 'date', 'funny', 'review_id', 'stars', 'text',
       'useful', 'user_id'],
      dtype='object')

In [25]:
# Preview the text column
df['text']

1       I love this place! My fiance And I go here atl...
2       Terrible. Dry corn bread. Rib tips were all fa...
4       Delicious healthy food. The steak is amazing. ...
5       This place sucks. The customer service is horr...
10      I have been an Emerald Club member for a numbe...
                              ...
689     Came here with my 2 year old daughter for our ...
4874    Great little restaurant. Not to many tables an...
564     Always great friendly service and fresh baked ...
3458    We were expecting amazing Thai food after all ...
4206    Sunday at 8p. Not many people here at all. We ...
Name: text, Length: 2610, dtype: object

### Apply lambda functions

In [27]:
type(df['text'])

pandas.core.series.Series

In [37]:
for x in df['text']:
    print(len(x.split()))

58
30
30
82
32
49
21
70
131
112
19
28
20
15
28
31
31
49
26
47
85
120
28
32
37
122
51
42
80
79
65
54
187
45
134
58
6
9
5
11
23
64
107
51
56
24
71
74
15
22
18
62
34
35
22
35
22
159
96
33
23
43
25
54
24
29
33
44
30
60
15
16
51
67
37
38
45
17
43
58
23
11
29
65
48
30
20
18
29
48
34
14
33
45
100
31
72
37
67
29
34
56
20
22
39
32
41
66
84
73
39
124
74
68
88
37
47
48
62
51
24
53
74
77
79
82
41
51
40
69
74
30
243
64
101
209
101
206
50
30
107
30
24
86
38
56
53
180
36
119
125
97
37
21
38
212
124
78
48
75
50
28
64
153
79
202
87
88
77
42
19
88
35
164
29
36
84
62
29
35
65
62
20
18
28
49
27
21
21
20
30
36
10
14
11
25
30
37
42
19
33
14
43
31
52
176
67
57
36
72
23
96
24
71
114
384
122
27
39
29
18
189
33
33
22
228
21
60
233
72
48
118
53
97
90
154
204
71
120
37
69
25
23
23
77
52
206
110
34
71
114
81
62
59
57
19
51
36
58
22
33
21
34
39
27
40
107
88
16
42
47
29
89
43
62
62
52
37
14
42
76
83
44
15
24
32
25
71
15
61
89
55
135
21
48
228
28
25
92
34
82
53
34
11
47
73
25
35
15
22
32
23
63
202
79
106
52
50
97
38
27
94
18
87
28
24
40
30
29
38
19
49
113
46
29
54
17
43
22
49
23
10
41
96
35
132
27
50
39
53
43
66
24
41
72
19
43
32
21
22
18
42
29
22
69
135
82
20
24
23
33
37
72
37
44
47
36
51
33
25
15
52
32
22
19
229
199
52
50
30
123
93
40
43
23
30
48
29
19
44
166
47
39
71
34
9
13
11
102
46
54
192
38
19
81
22
52
76
52
49
21
32
39
29
34
29
48
19
26
42
36
117
39
26
56
33
27
17
53
149
68
35
48
40
15
41
64
28
39
213
16
64
39
45
83
48
18
133
60
58
25
77
78
43
51
42
25
45
72
29
75
67
37
55
58
16
28
119
43
46
19
78
49
65
33
29
27
35
19
33
24
27
47
33
45
28
77
30
77
94
85
50
21
63
58
25
136
44
56
90
33
49
47
30
32
89
58
33
46
30
46
46
54
66
57
62
48
25
73
73
57
56
31
35
33
40
87
76
39
23
22
24
83
13
24
56
38
47
38
28
19
17
17
41
57
57
23
26
18
1
25
65
37
25
26
5
47
26
46
54
77
47
81
37
195
46
17
34
29
23
80
69
69
14
87
17
24
21
23
49
37
14
19
29
27
14
15
100
37
39
29
50
34
84
36
144
57
19
72
44
70
15
21
32
14
38
45
39
17
24
37
41
25
31
35
24
41
16
28
13
20
29
71
21
61
317
34
57
24
40
53
41
44
88
90
20
78
24
34
29
29
105
110
169
60
59
90
17
62
61
28
33
18
80
112
64
13
76
93
35
33
127
35
25
27
22
38
32
56
50
27
21
105
41
35
96
63
66
61
23
49
64
41
15
86
69
50
38
20
119
48
63
45
52
95
30
111
65
61
48
20
84
40
233
29
67
51
42
47
100
40
60
21
111
35
27
31
26
78
32
20
27
16
25
13
30
39
59
19
117
70
46
21
50
42
31
18
24
13
30
21
85
31
27
27
29
41
14
21
65
77
66
32
52
73
33
33
21
28
65
23
91
70
43
34
27
31
84
61
30
160
41
25
18
13
150
77
24
52
36
24
28
48
16
17
85
46
32
70
68
67
44
54
37
18
58
44
31
69
25
55
18
22
40
48
28
13
19
17
115
39
76
46
23
35
47
110
39
36
51
112
17
24
28
38
34
70
24
12
17
26
60
23
41
66
59
31
68
9
71
58
81
62
37
19
75
76
64
51
37
14
48
35
64
104
134
42
28
16
36
22
64
21
48
118
92
23
37
93
47
29
26
31
78
58
36
55
57
36
42
61
17
67
49
42
23
37
158
95
29
79
155
28
34
50
22
33
46
15
38
33
38
27
21
20
84
61
19
32
39
45
62
24
50
24
19
64
23
52
93
43
55
34
30
78
22
56
49
22
120
42
36
30
76
268
44
20
18
33
17
36
16
23
11
42
33
169
14
26
62
18
20
17
25
37
53
67
71
60
24
16
79
28
15
54
23
24
38
44
245
96
100
140
55
123
151
120
98
31
26
25
43
73
70
101
33
70
102
27
54
137
25
102
86
25
22
14
22
21
149
45
41
18
61
29
69
26
55
64
19
54
36
34
55
46
26
10
14
19
20
103
59
36
68
68
47
99
80
158
24
22
51
71
23
32
30
52
65
20
32
22
62
142
45
18
50
38
25
22
73
23
22
24
45
97
123
239
31
96
31
42
22
26
27
14
13
31
22
30
35
10
97
93
44
17
22
40
68
92
194
69
95
72
18
34
25
27
66
70
169
92
29
41
43
29
48
18
35
22
209
53
55
51
52
41
284
33
37
35
25
20
21
26
29
37
105
36
65
35
41
22
32
49
62
38
14
13
17
130
54
78
82
34
74
80
64
19
34
51
26
20
68
20
17
28
23
30
56
37
17
44
21
18
11
18
31
21
48
54
20
25
34
28
30
69
48
40
23
38
57
51
54
22
51
23
41
24
76
25
35
31
40
50
42
38
36
25
37
21
30
38
59
91
72
30
21
47
37
20
36
25
46
47
21
50
32
65
125
13
26
9
35
23
36
22
31
16
31
29
58
60
55
49
41
47
32
28
53
92
43
82
54
40
75
41
30
35
36
24
87
20
48
26
21
17
102
53
24
80
75
52
100
60
15
21
50
44
48
27
29
44
12
36
31
33
55
49
30
82
42
29
65
57
81
97
31
14
24
32
57
19
29
103
55
36
31
23
64
58
71
96
48
40
27
31
17
169
131
21
27
20
29
37
52
52
22
24
25
42
11
47
9
20
20
45
43
102
60
25
38
12
26
22
93
30
27
19
36
24
53
77
34
95
58
52
90
95
55
44
27
37
29
82
37
12
25
62
7
6
39
58
28
29
44
32
36
27
22
32
22
17
56
62
17
460
20
36
33
20
17
64
85
22
14
18
20
131
62
42
33
39
33
19
19
68
41
97
66
21
32
23
35
38
47
56
27
38
55
26
28
23
72
93
84
78
45
83
27
212
37
29
30
76
56
98
112
36
96
62
297
59
86
21
121
69
37
40
55
76
54
64
64
184
126
92
109
142
25
133
76
28
34
90
50
27
75
41
102
160
142
112
27
55
96
59
47
34
347
49
56
26
266
57
19
94
75
106
216
138
37
76
60
299
62
57
78
111
71
600
45
130
131
38
52
36
18
30
122
52
93
22
24
104
105
159
28
61
55
96
103
424
36
24
72
14
150
123
182
24
56
112
31
13
54
133
62
65
95
60
93
25
84
71
51
44
104
24
328
20
96
64
80
108
28
19
141
187
85
204
64
310
19
72
18
103
185
36
117
69
261
237
51
157
37
97
52
50
95
156
235
41
117
68
34
67
57
181
143
36
45
120
40
442
41
22
223
626
37
44
46
54
51
601
76
29
52
107
50
149
174
148
134
19
756
84
44
70
150
93
48
38
56
64
137
655
325
31
88
67
53
62
251
35
28
46
108
100
25
18
124
126
72
101
161
159
234
14
41
37
447
84
460
648
146
37
40
59
64
169
559
63
50
105
45
34
39
105
38
298
326
15
568
54
48
175
31
29
160
140
112
17
25
192
781
30
126
103
69
34
185
128
319
73
133
45
37
65
327
49
80
33
32
98
79
80
70
18
49
166
72
130
14
70
56
304
95
78
120
180
41
64
197
37
73
214
81
24
48
32
80
252
48
72
242
182
228
40
37
181
201
94
84
152
79
42
338
140
47
50
144
148
121
98
894
134
343
36
111
197
50
274
66
31
41
40
131
193
28
63
29
96
29
61
93
19
40
81
424
79
151
102
166
125
96
28
19
64
171
77
272
92
168
158
37
56
48
127
36
19
57
88
64
42
55
24
314
49
242
142
113
34
71
50
28
170
43
104
123
109
20
329
36
36
122
32
99
153
127
104
114
53
15
102
122
40
234
118
48
20
22
772
126
11
62
43
20
166
492
73
23
262
51
132
78
66
90
32
84
152
34
50
135
157
27
23
58
209
164
35
139
50
169
107
121
46
13
15
175
264
65
21
90
134
24
74
135
846
155
35
45
87
157
22
18
30
376
36
77
165
147
87
48
154
41
211
45
26
19
439
60
54
55
42
41
47
26
22
23
33
96
119
72
84
24
93
96
211
60
161
46
33
89
126
38
128
15
75
86
478
136
297
38
89
336
94
66
146
14
115
54
37
175
41
23
66
100
22
70
37
47
113
28
447
124
172
218
213
79
134
44
32
53
33
40
85
39
36
82
14
21
195
43
115
103
27
135
62
22
22
27
14
123
156
131
179
37
45
94
45
41
324
699
42
16
103
57
133
155
64
42
71
147
74
21
196
86
51
22
113
57
48
109
384
40
31
49
131
20
22
156
149
185
28
116
262
20
145
15
382
90
22
34
159
317
13
23
97
67
59
307
215
40
108
104
172
145
106
129
43
230
91
75
183
86
85
33
43
55
213
96
37
28
180
107
80
22
149
266
26
42
29
163
115
11
27
22
38
41
183
29
66
21
119
11
247
57
55
36
74
340
124
511
91
80
200
83
65
132
47
59
129
38
45
113
326
77
36
97
37
205
93
18
257
25
58
110
40
68
92
49
63
145
86
16
107
311
49
149
69
31
177
46
183
172
94
70
207
17
58
17
193
62
138
46
26
90
106
28
105
68
24
21
29
236
75
62
74
72
22
77
89
150
42
40
130
69
32
144
86
309
29
68
60
151
130
83
11
69
44
179
74
18
55
21
44
417
262
100
168
46
150
24
64
130
51
429
124
108
248
73
80
121
112
228
42
28
30
25
143
57
33
40
32
63
191
136
35
63
65
128
42
73
47
13
140
35
28
40
45
146
30
16
55
78
60
134
228
80
129
31
52
83
72
147
46
80
60
430
236
44
46
80
44
21
69
36
95
159
84
675
91
190
173
5
125
36
35
41
31
35
34
44
36
14
29
58
31
142
59
56
196
58
88
200
215
33
104
57
73
57
147
87
14
71
57
378
60
248
204
15
207
129
30
74
40
62
171
187
33
33
115
49
397
34
92
127
38
29
109
75
25
178
81
52
117
180
46
106
365
12
97
69
845
82
49
28
44
150
96
80
132
115
23
17
128
30
92
52
35
67
49
16
28
92
79
155
18
75
18
126
110
83
50
58
158
35
197
91
66
56
64
16
209
26
164
66
71
131
72
29
90
44
33
141
153
228
67
70
170
234
49
152
170
67
87
27
137
36
98
336
85
28
133
27
152
50
242
37
101
550
50
248
266
18
60
30
91
344
290
53
20
97
96
21
190
47
161
44
134
605
59
208
93
97
188
108
56
246
517
126
78
69
86
239
67
41
20
132
50
71
80
296
22
149
39
154
24
30
64
41
63
109
102
180
30
30
39
51
187
152
22
63
81
74
19
59
26
95
155
46
39
70
105
181
135
136
31
569
122
42
182
71
51
99
134
27
111
197
50
52
105
13
202
41
39
164
193
71
19
188
65
44
154
99
26
41
123
165
304
226
13
47
32
98
169
137
194
119
35
93
50
245
376
97
36
125
57
169
81
44
97
56
70
38
544
200
202
63
44
47
62
68
40
87
36
105
57
71
125
59
170
103
86
96
152
135
335
103
43
8
107
477
81
953
27
77
145
67
185
57
32
19
85
117
72
22
31
48
95
60
89
25
39
22
46
141
24
148
589
122
11
48
133
37
128
61
43
79
185
42

In [41]:
# Use the map and Lambda function to iterate through the text column and find the Length of each sentence
df['Review_Word_Length'] = df['text'].map(lambda x: len(x.split()))
df['Review_word_Length']

KeyError: 'Review_word_Length'

In [4]:
df.shape # Previously this was (2610, 9), now we have added a column

(2610, 10)

# Before you group any data, remember to confirm the data type and ensure it's in the right format.

### Group data

In [5]:
df.groupby('business_id')['stars'].mean().head()

business_id
-050d_XIor1NpCuWkbIVaQ    5.0
-0qht1roIqleKiQkBLDkbw    1.0
-3zffZUHoY8bQjGfPSoBKQ    5.0
-6tvduBzjLI1ISfs3F_qTg    5.0
-9nai28tnoylwViuJVrYEQ    5.0
Name: stars, dtype: float64

### Check for duplicates

Check how many we have:

In [6]:
df.duplicated().value_counts()

False    2277
True      333
dtype: int64

Visually inspect them:

In [7]:
# Use keep=False to keep all duplicates and sort_values to put duplicates next to each other
df[df.duplicated(keep=False)].sort_values(by='business_id')

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,Review_Word_Length
1729,-GY2fx-8udXPY8qn2HVBCg,0,2016-08-30,0,yQ6P1_CvM94wMLYw1T0UWA,5,Just opened a new account today. So far I am ...,1,sZfZGrI592euyacKUcwQYg,55
1729,-GY2fx-8udXPY8qn2HVBCg,0,2016-08-30,0,yQ6P1_CvM94wMLYw1T0UWA,5,Just opened a new account today. So far I am ...,1,sZfZGrI592euyacKUcwQYg,55
754,-LRlx2j9_LB3evsRRcC9MA,0,2017-10-07,0,kUqPsZmWwLIMSstGHhWssA,5,The vet took the time to explain what was poss...,0,VgaYZ7004pTwEDSDWR6u4Q,33
754,-LRlx2j9_LB3evsRRcC9MA,0,2017-10-07,0,kUqPsZmWwLIMSstGHhWssA,5,The vet took the time to explain what was poss...,0,VgaYZ7004pTwEDSDWR6u4Q,33
2767,-MKWJZnMjSit406AUKf7Pg,0,2015-01-03,2,rJhrQD3-b9GjTso0dxIkwg,1,Drove 37 miles on a Saturday at 12:30pm for lu...,0,kzP96uX8TUMmmvLtd-I3RQ,18
...,...,...,...,...,...,...,...,...,...,...
2193,zKw09ftu1730wEIZBZPoFg,3,2015-01-04,0,JV-yxKxMFp-d0rLDc_2_6w,5,So relaxing combined with the meditation and ...,5,3mZFkwfa6XV0BBazRTva9w,31
496,zg5rJfgT4jhzg1d6r2twnA,0,2014-06-21,0,Zbj0HgdN3AT4l-mbH-EfjA,3,Burger week\r\n\r\n1. Blazing Pineapple Burger...,0,UGW-9bbBEB3eP1o6mWD_WA,62
496,zg5rJfgT4jhzg1d6r2twnA,0,2014-06-21,0,Zbj0HgdN3AT4l-mbH-EfjA,3,Burger week\r\n\r\n1. Blazing Pineapple Burger...,0,UGW-9bbBEB3eP1o6mWD_WA,62
988,ziv21pDfyrgdhlrlNIgDfg,0,2016-08-11,0,fus9odxu9bjE2lSxfwNfdw,5,Get this!!! Wow Karlo is amazing and best cus...,2,ywjqPgnMrDZKOhA33v92Cw,62
988,ziv21pDfyrgdhlrlNIgDfg,0,2016-08-11,0,fus9odxu9bjE2lSxfwNfdw,5,Get this!!! Wow Karlo is amazing and best cus...,2,ywjqPgnMrDZKOhA33v92Cw,62

### Remove duplicates

In [8]:
df = df.drop_duplicates()
df.shape # Previously this was (2610, 10), now we have dropped duplicate rows

(2277, 10)

### Recheck for duplicates

In [9]:
df.duplicated().value_counts()

False    2277
dtype: int64

In [10]:
# Duplicates should no longer exist
df[df.duplicated(keep=False)].sort_values(by='business_id')

Empty DataFrame
Columns: [business_id, cool, date, funny, review_id, stars, text, useful, user_id, Review_Word_Length]
Index: []

### Create pivot tables

In [11]:
# This transforms the data into a person by person spreadsheet and what stars they gave various restaurants
# Most values are NaN (null or missing) because people only review a few restaurants of those that exist
usr_reviews = df.pivot(index='user_id', columns='business_id', values='stars')
usr_reviews.head()

business_id,-050d_XIor1NpCuWkbIVaQ,-0qht1roIqleKiQkBLDkbw,-3zffZUHoY8bQjGfPSoBKQ,-6tvduBzjLI1ISfs3F_qTg,-9nai28tnoylwViuJVrYEQ,-C8sSrFqaCxp51pyo-fQLQ,-Dnh48f029YNugtMKkkI-Q,-FLnsWAa4AGEW4NgE8Fqew,-G7MPSNBpxRJmtrJxdwt7A,-GY2fx-8udXPY8qn2HVBCg,...,zdE82PiD6wquvjYLyhOJNA,zdd3hyxB8ylYV6RcNe347Q,zg5rJfgT4jhzg1d6r2twnA,ziv21pDfyrgdhlrlNIgDfg,zkhBU5qW_zCy0q4OEtIrsA,ztP466jMUMtqLwwHqXbk9w,zw9_mqWBn1QCfZg88w0Exg,zwNLJ2VglfEvGu7DDZjJ4g,zzYaAiC0rLNSDiFQlMKOEQ,zzgSiOnuUjnBnmfR-ZG4ww
user_id,,,,,,,,,,,,,,,,,,,,,
-0biHfjE0soSptbU5G3nug,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-2K0yp7lBT_JUOzGkpdJ_g,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-Opvc9hAWllZSSPDUsD7NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-Zdxj4wuj4D_899B7tPE3g,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-_iULENf28RbqL2k0ja5Xw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Summary

In this brief introduction, you learned the acronym ETL and got to preview a few examples of ETL processes using pandas.